_target_: robot_io.cams.kinect4.kinect4.Kinect4
_recursive_: false
device: 0
align_depth_to_color: true
resolution: '1080p'
undistort_image: true
#resize_resolution: [200, 150]
#crop_coords: [301, 623, 516, 946]
fps: 30