_target_: tacorl.evaluation.rollout_generator.LongHorizonRolloutGenerator
data_dir: ~/tacorl/calvin
start_end_tasks: ~/tacorl/calvin/start_end_tasks.json
tasks_per_rollout: 2
strategy: shortest
min_seq_len: 10
max_seq_len: 300
