_target_: calvin_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.3, 0.15, 0.6]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342]
surfaces: []
objects:
  fixed_objects:
    table:
      file: table/hightable.urdf
      initial_pos: [ 0.3, 0.7, 0.02 ]
      initial_orn: [0, 0, 0]
  movable_objects:
    plate:
      file: 029_plate/google_16k/textured.urdf
      initial_pos: [ 0.35, 0.72, 0.61 ]
      initial_orn: [0, 0, 0]
    thuna:
      file: ais_objects/thuna/thuna.urdf
      initial_pos: [ -0.1, 0.9, 0.65 ]
      initial_orn: [0, 0, 0]
    banana:
      file: 011_banana/demo/banana_vhacd.urdf
      initial_pos: [ 0.5, 0.9, 0.61 ]
      initial_orn: [0, 0, 0]
    bowl:
      file: 024_bowl/google_16k/textured.urdf
      initial_pos: [-0.1, 0.72, 0.75]
      initial_orn: [0, 0, 0]
