_target_: calvin_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.3, 0.15, 0.6]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342]
surfaces: []
objects:
  fixed_objects:
    table:
      file: own_objects/modified_table_new_handles/playtable_modified.urdf
      initial_pos: [0.7, 1.0, 0]
      initial_orn: [0, 0, 3.141592653589793]
      joints:
        top_left_door_joint:
          initial_state: 0  # revolute
        slide_door_joint:
          initial_state: 0  # prismatic
    drawer:
      file: own_objects/drawer/drawer.urdf
      initial_pos: [0.475, 1.0, -0.004]
      initial_orn: [0, 0, 3.141592653589793]
      joints:
        drawer_joint:
          initial_state: 0  # prismatic
