# @package _global_
defaults:
  - /scene: calvin_scene_D
  - /robot: panda_longer_finger
  - /cameras: all_cameras
  - /env: goal_conditioned
  - /datamodule/transform_manager@evaluation.transform_manager: rl
  - _self_

data_path: data  
module_path: /mnt/SSD/tacorl/models/cql
short_horizon: True