# @package _global_
defaults:
  - cql
  - rollout_generator@evaluation.single_task_rollout_generator: single_task
  - _self_

eval_type: short_horizon
filename: cql_easy_tasks.json

data_dir: ~/tacorl/calvin
evaluation:
  single_task_rollout_generator:
    data_dir: ${data_dir}
    start_end_tasks: ${data_dir}/start_end_tasks.json