# @package _global_
defaults:
  - cql
  - rollout_generator@evaluation.long_horizon_seq_rollout_generator: long_horizon_sequential
  - _self_

eval_type: long_horizon_sequential
filename: cql_lh_seq_easy_tasks.json

data_dir: ~/tacorl/calvin
evaluation:
  long_horizon_seq_rollout_generator:
    data_dir: ${data_dir}
    start_end_tasks: ${data_dir}/start_end_tasks.json