# @package _global_
defaults:
  - base
  - rollout_manager@evaluation.rollout_manager: latent_plan_rollout
  - _self_

module_path: ~/tacorl/models/lmp

env:
  max_episode_steps: 180

evaluation:
  rollout_manager:
    plan_duration: 15