# @package _global_
defaults:
  - lmp
  - rollout_generator@evaluation.long_horizon_rollout_generator: long_horizon
  - _self_

eval_type: long_horizon
filename: lmp_lh_easy_tasks.json

env:
  max_episode_steps: 300

data_dir: ~/tacorl/calvin
evaluation:
  long_horizon_rollout_generator:
    data_dir: ${data_dir}
    start_end_tasks: ${data_dir}/start_end_tasks.json