# @package _global_
defaults:
  - tacorl
  - rollout_generator@evaluation.single_task_rollout_generator: hard_single_task
  - _self_

eval_type: short_horizon
filename: tacorl_hard_tasks.json

data_dir: ~/tacorl/calvin
evaluation:
  single_task_rollout_generator:
    data_dir: ${data_dir}
    start_end_tasks: ${data_dir}/start_end_tasks.json