defaults:
  - /networks/encoder@networks.rgb_static: r3m_encoder
  - /networks/encoder@networks.rgb_gripper: lmp_vision_encoder

_target_: tacorl.networks.representation.representation_network.LateFusion
_recursive_: False