defaults:
  - /networks/encoder@networks.rgb_static: simple_encoder
  - /networks/encoder@networks.rgb_gripper: simple_encoder

_target_: tacorl.networks.representation.representation_network.LateFusion
_recursive_: False

networks:
  rgb_gripper:
    input_width: 84
    input_height: 84