defaults:
  - dataset: relay_imitation_learning
  - transform_manager: rl

_target_: tacorl.datamodule.basic_data_module.BasicDataModule
_recursive_: false
data_dir: ~/tacorl/calvin
batch_size: 64
num_workers: 4
val_percentage: 0.1
train_percentage: 0.1
shuffle_val: false