validation:  
  rgb_static:
    - _target_: torchvision.transforms.Resize
      size: [128, 128]
    - _target_: tacorl.utils.transforms.ScaleImageTensor # 0 to 255 -> 0 to 1
    - _target_: torchvision.transforms.Normalize #0 to 1 -> -1 to 1
      mean: [0.5,]
      std: [0.5,]
  rgb_gripper:
    - _target_: torchvision.transforms.Resize
      size: [84, 84]
    - _target_: tacorl.utils.transforms.ScaleImageTensor # 0 to 255 -> 0 to 1
    - _target_: torchvision.transforms.Normalize #0 to 1 -> -1 to 1
      mean: [0.5,]
      std: [0.5,]
  depth_static:
    - _target_: torchvision.transforms.Resize
      size: [128, 128]    
    - _target_: tacorl.utils.transforms.ScaleDepthTensor # min to max -> 0 to 1
      min_depth: 3.5
      max_depth: 6.3
    - _target_: tacorl.utils.transforms.ColorizeDepth
      colormap: jet
    - _target_: torchvision.transforms.Normalize #0 to 1 -> -1 to 1
      mean: [0.5,]
      std: [0.5,]
  depth_gripper:
    - _target_: torchvision.transforms.Resize
      size: [84, 84]
    - _target_: tacorl.utils.transforms.ScaleDepthTensor # min to max -> 0 to 1
      min_depth: 0.0
      max_depth: 2.0
    - _target_: tacorl.utils.transforms.ColorizeDepth
      colormap: jet
    - _target_: torchvision.transforms.Normalize #0 to 1 -> -1 to 1
      mean: [0.5,]
      std: [0.5,]
  # robot_obs:
  #   - _target_: tacorl.utils.transforms.NormalizeVector
  # scene_obs:
  #   - _target_: tacorl.utils.transforms.NormalizeVector